### ISSUE TITLE
Typescript version

### ISSUE THREAD

**Issue by user753** [recksjs/recks-starter-project#4]
I would like to try Recks but with typescript.

**Comment by kosich** [comment]
Definitely agree, TypeScript would add a lot to the project! Thank you for reporting this!

I haven't yet figured out how to setup JSX types to match Observable content, e.g.:

```jsx
<App title="hello" />
```

In **React** it's
```ts
function App(props: { title: string }) : JSX
```

In **Recks** it's 
```ts
function App(props: Observable<{ title: string}> ) : JSX | Observable<JSX> | Promise<JSX>
```

The fix might be anywhere from simple compiler setup to parser rewrite 🙂
I will return to this issue when the core functionality is more stable.

**Comment by user753** [comment]
It is one of the questions that I cannot figure out without types, how does props work?
Does it mean I cannot do something like 
```<App title="foo"/>``` 
and I need to do
```
<App {...of({title="foo"})}/>
```
Maybe it could be 
```
function App(props: { title: string | Observable<string> }) : JSX
```
instead?

**Comment by kosich** [comment]
Yeah, in the parent you use simple static properties:

```jsx
<Header title="foo" />
```

Recks will track all property changes and will push updates to child's `props$` stream.

E.g. a header that is updated from the parent:

```jsx
function App(){
  return timer(0, 1000).pipe(
    map(t => <Header title={ t }  />) // <- update title each second
  );
}

function Header(props$) {
  const title$ = props$.pipe( pluck('title') ); // <- created only once per component lifetime

  return <h1>{ title$ }</h1> // <- use stream of title$ updates
}
```

So the parent sets it statically (classic JSX style) and the child gets updates as a stream — the child will choose how to react and to which prop changes.

And you can rely on `Header` function to be called only once for a component!
It's handy because you can create all your observables/subjects and do static computations there! E.g:

```jsx
function App(){
  // create local state Subject
  const state$ = new Subject();

  // compute view based on it
  const value$ = state$.pipe(
    startWith(0),
    scan((acc, curr) => acc + curr)
  );

  // create a click handler
  const onClick = () => state$.next();

  return <div>
    { value$ }
    <button onClick={ onClick }>add 1</button>
  </div>
}
```

I tried to reflect these ideas in docs [lifecycle](https://recks.gitbook.io/recks/api/lifecycle) and [subscomponents#props](https://recks.gitbook.io/recks/api/subcomponents#props) sections
(please, ping me back if you'll find them unclear!)

**Comment by user753** [comment]
Thanks. Does it mean that there is a difference between props and children and
it is possible to pass Observable to children, but only static values to props?
> (please, ping me back if you'll find them unclear or have an idea how to improve them)

I think the example of how to pass part of props could be helpfull, something like this
```
  funciton Bar(props: {value: number}){
    return <div> {props.value} </div>
  }

  function Foo(props: {x: number, y: number}){
    return <Bar value={props.x}/>
  }
```

**Comment by kosich** [comment]
> Does it mean that there is a difference between props and children and
it is possible to pass Observable to children, but only static values to props?

That's correct!

_I'm planning to add support for passing props as Observable, like `<div title={ stream$ }>` but haven't found a good way to do that yet — want the API to be distinct, like angular's [] for input and () for output props._

Currently one should use `stream$.pipe( map(data => <div title={ data } />) )` to update props
So to apply this to your example:

```jsx
function Bar(props$: Observable<{value: number}>){
  return <div>{ props$.pipe( pluck('value') )} </div>
}

function Foo(props$: Observable<{x: number, y: number}>){
  return props$.pipe( pluck('x'), map(x => <Bar value={x}/> ) )
}
```

_will add this to examples!_

AND we can easily create a wrapper for Observable components that would make em "static" (react-like), e.g.:

```jsx
// wrapping function will map each update to props$
// and will call 'static' component function
function wrap(staticComponent) {
  return props$ => props$.pipe(
    map(props => staticComponent(props))
  )
}

const Bar = wrap((props: {value: number}) => {
  return <div>{ props.value }</div>
});

const Foo = wrap((props: {x: number, y: number}) => {
  return <Bar value={ props.x }/>
});
```

_It's hard to turn a react component into recks-like, but turning recks component to react-like is easier!_

Does this make any sense? :)

**Comment by user753** [comment]
>Does this make any sense? :)

Yes, thanks. It would be interesting to see the final version of recks api.

**Comment by kosich** [comment]
I have some ideas as to where to dig (like observable props and static wrapper)

But that is highly dependent on user's feedback!

So keep an eye on the project updates. And if you have more ideas and thoughts — please, share! :)

**Comment by user753** [comment]
>I haven't yet figured out how to setup JSX types to match Observable content, e.g.:

Did you consider to use functions as alternative to jsx?
https://github.com/jorgebucaran/hyperapp/tree/master/pkg/html
Jsx is great, but I think with functions you will not have any limitations.

**Comment by kosich** [comment]
There are pros and cons with JSX:
I do have several limitations with it, yet I like it's HTML-like style — it helps distinguish well view in JS/TS.

I'll have to read more about that. Thank you for the hint!

**Comment by kosich** [comment]
TS support was added with [Recks v0.0.14](https://github.com/recksjs/recks/releases/tag/v0.0.14) 🙌
You can try it by cloning this template repo and running project locally

Please, feel free to add comments and/or reopen issue if you think it is not resolved

**Comment by user753** [comment]
@kosich Cool, thanks. In what cases Observable props should be used?
```
function Foo(props$: Observable<{ value: string}> ) {
    return <div>{props$.pipe(map(x => x.value))}</div>
}

function Bar(props: { value: string} ) {
    return <div>{props.value}</div>
}
```
And I can use them identically
```
    const timer$ = timer(0, 1000);
    {timer$.pipe(map(value => <Foo value={value}/>))}
    {timer$.pipe(map(value => <Bar value={value}/>))}
```

**Comment by kosich** [comment]
@user753 , oops, that's a type definition issue on Recks! Currently components **always** receive Observable props, so following type should cause a TS error:

```ts
<Bar value={value}/>

// INVALID:
function Bar(props: { value: string} ) {…}

// VALID:
function Bar(props: Observable<{ value: string}>) {…}
```

I'll create an issue for this in [Recks repo](https://github.com/recksjs/recks)! Thanks!

---

**NOTE 1:** While there are cases where one would prefer simple `props => JSX` functions instead of `Observable props => Observable JSX`, we've discussed this previously. Here's an updated TS version:

```ts
function discrete<T>(fn: (props: T) => any) {
  return (props$: Observable<T>) => props$.pipe(map(fn));
}
```

and then

```tsx
export const Bar = discrete((props: { title: string }) => <h1>{ props.title }</h1>);
```


**NOTE 2:** Also, latest Recks update ([0.0.14](https://github.com/recksjs/recks/releases/tag/v0.0.14)) allows direct use of Observables in **intrinsic** elements, e.g.:
```tsx
<img src={ stream$ } />
```

which is analogue of ↓, just less verbose

```tsx
{ stream$.pipe(map(src => <img src={ src } />)) }
```

And I'm planning to add a similar feature to **components** — though with components it's unclear how exactly the API should look like: `props: Observable<{ title: string }>` or `props: { title: Observable<string> }` or a combination of two, or something else. I've created an issue to discuss that https://github.com/recksjs/recks/issues/6

**Comment by user753** [comment]
>  oops, that's a type definition issue on Recks! 

I thought it was a feature. Is there a reason to remove this? Right now it seems to work fine.

**Comment by kosich** [comment]
This is purely **experimental feature** ! 😊

The reason it works is that under the hood it wraps Observable `props$` in a Proxy, that lets us access values on Observable updates. I've created a standalone library to do that https://github.com/kosich/rxjs-proxify (here's an article for details ["Turn a Stream of Objects into an Object of Streams"](https://dev.to/rxjs/turn-a-stream-of-objects-into-an-object-of-streams-2aed))

So the type is actually:

```ts
function Bar(props: Observable<{ title: string }> & { title: Observable<string> }) { … };
```

_(it's simultaneously Observable of Objects and Object of Observables 🤯)_

And since Recks accepts Observables as children, the `<div>{props.value}</div>` will work — but note that `props.value` is actually an Observable!

**This feature will probably be changed/upgraded in the following updates.**

---

As to the reason why we can't simultaneously support `function Foo(props$: Observable<{ value: string}>) {` and `function Bar(props: { value: string} ) {` — is that alas I can't detect statically whether the Component is dynamic or not, and therefore should I call it with `Observable<Props>` or just `Props`. Above-mentioned `discrete` fn can help with that.

**Speculation**: maybe in the future we'll have dynamic components (that operate on Observables) as class-defined components, while "discrete" components that just map props on JSX will be functions. Components API is something I still want to improve, and I thank you for participating in a search for better API !
